inventory = ("BOW", "SWORD", "WAND", "BOMB")

input("WELCOME TO ADVENTURE SIMULATOR! WHAT IS YOUR NAME TRAVELER?")

print("AS YOU ARE TRAVELING YOU COME ACORSS MERLIN THE GREAT, HE APPROACHES YOU WITH A QUEST TO DEFEAT THE FOUR GREAT CREATURES WHO HAVE BEEN TERRIFYING THE LANDS. WILL YOU BE THE FIRST TO COME BACK ALIVE? ")

def inventory(WEAPON_CHOICE, inventory):
    
    for i in range(len(inventory)):
        str = "PICK "
